name: Terraform Workflow

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'
  pull_request:
    branches:
      - main

jobs:
  terraform-job:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
      GITHUB_OWNER: ${{ secrets.TF_GITHUB_OWNER }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Print vars
      run: |
        echo "$GITHUB_OWNER"
        echo "$GITHUB_TOKEN"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      if: github.event_name == 'push' && github.ref_type == 'branch'
      run: terraform validate

    - name: Terraform Apply
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      run: terraform apply -auto-approve
