name: Terraform Workflow

on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    branches:
      - main

jobs:
  terraform-job:
    runs-on: ubuntu-latest

    steps:
    - name: Debug Information
      run: |
        echo "Event Name: $GITHUB_EVENT_NAME"
        echo "Ref: $GITHUB_REF"
        echo "Branch Name: $GITHUB_REF_NAME"
        echo "Is Push to Branch: ${{ github.event_name == 'push' && github.ref_type == 'branch' }}"
        echo "Is Pull Request to Main: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}"
        
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      if: github.event_name == 'push' && github.ref_type == 'branch'
      run: terraform validate

    - name: Terraform Apply
      if: github.event_name == 'pull_request' && github.event.action == 'opened'
      run: terraform apply -auto-approve
